### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by Alim-faraji** [QuantEcon/lecture-julia.myst#13]
There are some tests failing. 
````bash
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\ifp.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\lqcontrol.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\mccall_model_with_separation.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\optgrowth.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\perm_income.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\wald_friedman.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\lqramsey.log
````

**Comment by Alim-faraji** [comment]
I commented out these tests, but after executing the codes again, there were some new failed tests showing in the reports.

**Comment by Alim-faraji** [comment]
An error which I couldn't figure out:

````
Traceback (most recent call last):
  File "/home/alim/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/alim/.local/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/alim/.local/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/alim/.local/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/alim/.local/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/alim/.local/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/alim/.local/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ϕ_1, ϕ_2, ϕ_3, ϕ_4 = 0.5, -0.2, 0, 0.5
σ = 0.01
ν = 0.01 # growth rate

# A matrix should be n x n
A = [ϕ_1 ϕ_2 ϕ_3 ϕ_4;
       1   0   0   0;
       0   1   0   0;
       0   0   1   0]

# B matrix should be n x k
B = [σ, 0, 0, 0]

D = [1 0 0 0] * A
F = [1, 0, 0, 0] ⋅ vec(B)

amf = AMF_LSS_VAR(A, B, D, F, ν)

T = 150
x, y = simulate(amf.lss, T)

plots = plot(layout = (2, 1))

plot!(plots[1], 1:T, y[amf.nx + 1, :], color = :black, lw = 2, label = "")
plot!(plots[1], title =  "A particular path of y_t")
plot!(plots[2], 1:T, y[1, :], color = :green, lw = 2, label = "")
plot!(plots[2], seriestype = :hline, [0], color = :black, lw = 2, linestyle=:dashdot,
      label = "")
plot!(plots[2], title = "Associated path of x_t")

plot(plots)
------------------

MethodError: no method matching get(::Int64, ::Symbol, ::Int64)
[0mClosest candidates are:
[0m  get([91m::Union{Tables.AbstractColumns, Tables.AbstractRow}[39m, ::Union{Integer, Symbol}, ::Any) at /home/alim/.julia/packages/Tables/gg6Id/src/Tables.jl:185
[0m  get([91m::DataStructures.DefaultDict[39m, ::Any...) at /home/alim/.julia/packages/DataStructures/ixwFs/src/delegate.jl:21
[0m  get([91m::DataStructures.PriorityQueue[39m, ::Any, ::Any) at /home/alim/.julia/packages/DataStructures/ixwFs/src/priorityqueue.jl:176
[0m  ...

Stacktrace:
  [1] get_thickness_scaling(kw::Int64)
    @ Plots ~/.julia/packages/Plots/YVapH/src/utils.jl:579
  [2] get_thickness_scaling(series::Plots.Series)
    @ Plots ~/.julia/packages/Plots/YVapH/src/utils.jl:582
  [3] gr_set_line(lw::Int64, style::Symbol, c::RGBA{Float64}, s::Plots.Series)
    @ Plots ~/.julia/packages/Plots/YVapH/src/backends/gr.jl:372
  [4] gr_draw_segments(series::Plots.Series, x::UnitRange{Int64}, y::Vector{Float64}, fillrange::Nothing, clims::Tuple{Float64, Float64})
    @ Plots ~/.julia/packages/Plots/YVapH/src/backends/gr.jl:1719
  [5] gr_add_series(sp::Plots.Subplot{Plots.GRBackend}, series::Plots.Series)
    @ Plots ~/.julia/packages/Plots/YVapH/src/backends/gr.jl:1641
  [6] gr_display(sp::Plots.Subplot{Plots.GRBackend}, w::Measures.AbsoluteLength, h::Measures.AbsoluteLength, viewport_canvas::Vector{Float64})
    @ Plots ~/.julia/packages/Plots/YVapH/src/backends/gr.jl:955
  [7] gr_display(plt::Plots.Plot{Plots.GRBackend}, fmt::String)
    @ Plots ~/.julia/packages/Plots/YVapH/src/backends/gr.jl:646
  [8] _show(io::Base64.Base64EncodePipe, #unused#::MIME{Symbol("image/png")}, plt::Plots.Plot{Plots.GRBackend})
    @ Plots ~/.julia/packages/Plots/YVapH/src/backends/gr.jl:1897
  [9] show(io::Base64.Base64EncodePipe, m::MIME{Symbol("image/png")}, plt::Plots.Plot{Plots.GRBackend})
    @ Plots ~/.julia/packages/Plots/YVapH/src/output.jl:215
 [10] base64encode(::Function, ::MIME{Symbol("image/png")}, ::Vararg{Any, N} where N; context::Nothing)
    @ Base64 /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Base64/src/encode.jl:209
 [11] base64encode
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Base64/src/encode.jl:206 [inlined]
 [12] _ijulia_display_dict(plt::Plots.Plot{Plots.GRBackend})
    @ Plots ~/.julia/packages/Plots/YVapH/src/ijulia.jl:50
 [13] display_dict(plt::Plots.Plot{Plots.GRBackend})
    @ Plots ~/.julia/packages/Plots/YVapH/src/init.jl:77
 [14] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [15] invokelatest
    @ ./essentials.jl:706 [inlined]
 [16] execute_request(socket::ZMQ.Socket, msg::IJulia.Msg)
    @ IJulia ~/.julia/packages/IJulia/e8kqU/src/execute_request.jl:112
 [17] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [18] invokelatest
    @ ./essentials.jl:706 [inlined]
 [19] eventloop(socket::ZMQ.Socket)
    @ IJulia ~/.julia/packages/IJulia/e8kqU/src/eventloop.jl:8
 [20] (::IJulia.var"#15#18")()
    @ IJulia ./task.jl:406
MethodError: MethodError: no method matching get(::Int64, ::Symbol, ::Int64)
[0mClosest candidates are:
[0m  get([91m::Union{Tables.AbstractColumns, Tables.AbstractRow}[39m, ::Union{Integer, Symbol}, ::Any) at /home/alim/.julia/packages/Tables/gg6Id/src/Tables.jl:185
[0m  get([91m::DataStructures.DefaultDict[39m, ::Any...) at /home/alim/.julia/packages/DataStructures/ixwFs/src/delegate.jl:21
[0m  get([91m::DataStructures.PriorityQueue[39m, ::Any, ::Any) at /home/alim/.julia/packages/DataStructures/ixwFs/src/priorityqueue.jl:176
[0m  ...

````

**Comment by jlperla** [comment]
@Alim-faraji 

I would make sure that the notebook works on its own before trying to run it though automatically.

This one looks like there was a change in the plots package between versions and you will need to figure out the new way to do it after the upgrade

**Comment by Alim-faraji** [comment]
When I run the code cells in order, they all execute with no error. But this error raises in the build.

**Comment by jlperla** [comment]
My guess is that the build is activating a different project file, or maybe not doing an activation, than you are when you run it yourself.  I would triple check that the Project and Manifest files are in both and that an `activate` has been done on both.

**Comment by Alim-faraji** [comment]
It was because of the way the layouts in the plots were defined. I changed
```
plots = plot(layout = (2, 1))
--some code--
plot(plots)
```
to 
```
plots = [plot(), plot()]
--some code --
plot(plots[1], plots[2], layout = (2,1))
```
And then it was fine.

**Comment by Alim-faraji** [comment]
All tests are passing now. I'm closing this issue.
