### ISSUE TITLE
Issue with amss after upgrade

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#308]
The error I am getting in the logs is listed below.  I would walk through it slowly to see what is going on, and compare to the Julia 1.10 as discussed in the #307 issue.

Inexact errors usually mean something became a `NaN` because of dividing by zero or taking a negative number to a power which isn't a real number, etc.
```
Traceback (most recent call last):
  File "/home/jlperla/anaconda3/envs/lecture-julia.myst/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/jlperla/anaconda3/envs/lecture-julia.myst/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jlperla/anaconda3/envs/lecture-julia.myst/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jlperla/anaconda3/envs/lecture-julia.myst/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/jlperla/anaconda3/envs/lecture-julia.myst/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/jlperla/anaconda3/envs/lecture-julia.myst/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/jlperla/anaconda3/envs/lecture-julia.myst/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
time_example = CRRAModel(;G = [0.1, 0.1, 0.1, 0.2, 0.1, 0.1],
                         Theta = ones(6)) # Theta can in principle be random

time_example.Pi = [0.0 1.0 0.0 0.0 0.0 0.0;
                   0.0 0.0 1.0 0.0 0.0 0.0;
                   0.0 0.0 0.0 0.5 0.5 0.0;
                   0.0 0.0 0.0 0.0 0.0 1.0;
                   0.0 0.0 0.0 0.0 0.0 1.0;
                   0.0 0.0 0.0 0.0 0.0 1.0]

# Initialize mugrid for value function iteration
mugrid = range(-0.7, 0.01, length = 200)

time_example.transfers = true  # Government can use transfers
time_sequential = SequentialAllocation(time_example) # Solve sequential problem

time_bellman = RecursiveAllocation(time_example, mugrid)

sHist_h = [1, 2, 3, 4, 6, 6, 6]
sHist_l = [1, 2, 3, 5, 6, 6, 6]

sim_seq_h = simulate(time_sequential, 1.0, 1, 7, sHist_h)
sim_bel_h = simulate(time_bellman, 1.0, 1, 7, sHist_h)
sim_seq_l = simulate(time_sequential, 1.0, 1, 7, sHist_l)
sim_bel_l = simulate(time_bellman, 1.0, 1, 7, sHist_l)

using Plots

titles = hcat("Consumption", "Labor Supply", "Government Debt",
              "Tax Rate", "Government Spending", "Output")
sim_seq_l_plot = hcat(sim_seq_l[1:3]..., sim_seq_l[4],
                      time_example.G[sHist_l],
                      time_example.Theta[sHist_l] .* sim_seq_l[2])
sim_bel_l_plot = hcat(sim_bel_l[1:3]..., sim_bel_l[5],
                      time_example.G[sHist_l],
                      time_example.Theta[sHist_l] .* sim_bel_l[2])
sim_seq_h_plot = hcat(sim_seq_h[1:3]..., sim_seq_h[4],
                      time_example.G[sHist_h],
                      time_example.Theta[sHist_h] .* sim_seq_h[2])
sim_bel_h_plot = hcat(sim_bel_h[1:3]..., sim_bel_h[5],
                      time_example.G[sHist_h],
                      time_example.Theta[sHist_h] .* sim_bel_h[2])
p = plot(size = (920, 750), layout = (3, 2),
         xaxis = (0:6), grid = false, titlefont = Plots.font("sans-serif", 10))
plot!(p, title = titles)
for i in 1:6
    plot!(p[i], 0:6, sim_seq_l_plot[:, i], marker = :circle, color = :black,
          lab = "")
    plot!(p[i], 0:6, sim_bel_l_plot[:, i], marker = :circle, color = :red,
          lab = "")
    plot!(p[i], 0:6, sim_seq_h_plot[:, i], marker = :utriangle, color = :black,
          lab = "")
    plot!(p[i], 0:6, sim_bel_h_plot[:, i], marker = :utriangle, color = :red,
          lab = "")
end
p
------------------

----- stdout -----
diff = 0.019541811403379114
----- stdout -----
diff = 0.02029660452240845
----- stdout -----
diff = 0.018252901676510072
----- stdout -----
diff = 0.01732330163767122
----- stdout -----
diff = 0.0031325418440225337
----- stdout -----
diff = 0.0009645419766248225
----- stdout -----
diff = 0.00042579228255786673
----- stdout -----
diff = 0.00036342521821958824
----- stdout -----
diff = 0.00032679255217972085
----- stdout -----
diff = 0.00029387229120929646
----- stdout -----
diff = 0.00026447739141347324
----- stdout -----
diff = 0.00023803650678640254
----- stdout -----
diff = 0.0002142287734397143
----- stdout -----
diff = 0.00019279780504228292
----- stdout -----
diff = 0.0001735091765435803
----- stdout -----
diff = 0.00015615908664984014
----- stdout -----
diff = 0.00014054590902726154
----- stdout -----
diff = 0.00012649574833402226
----- stdout -----
diff = 0.00011397774745936076
----- stdout -----
diff = 0.0001025633783083926
----- stdout -----
diff = 9.25715117615316e-5
------------------

InexactError: Int64(NaN)
Stacktrace:
  [1] [0m[1mInt64[22m
[90m    @[39m [90m./[39m[90m[4mfloat.jl:994[24m[39m[90m [inlined][39m
  [2] [0m[1mconvert[22m
[90m    @[39m [90m./[39m[90m[4mnumber.jl:7[24m[39m[90m [inlined][39m
  [3] [0m[1m_round_convert[22m
[90m    @[39m [90m./[39m[90m[4mrounding.jl:480[24m[39m[90m [inlined][39m
  [4] [0m[1mround[22m
[90m    @[39m [90m./[39m[90m[4mrounding.jl:479[24m[39m[90m [inlined][39m
  [5] [0m[1mround[22m
[90m    @[39m [90m./[39m[90m[4mrounding.jl:477[24m[39m[90m [inlined][39m
  [6] [0m[1m(::FindFirstFunctions.Guesser{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}})[22m[0m[1m([22m[90mx[39m::[0mFloat64[0m[1m)[22m
[90m    @[39m [32mFindFirstFunctions[39m [90m~/.julia/packages/FindFirstFunctions/n3FjO/src/[39m[90m[4mFindFirstFunctions.jl:250[24m[39m
  [7] [0m[1msearchsortedlastcorrelated[22m
[90m    @[39m [90m~/.julia/packages/FindFirstFunctions/n3FjO/src/[39m[90m[4mFindFirstFunctions.jl:296[24m[39m[90m [inlined][39m
  [8] [0m[1mget_idx[22m[0m[1m([22m[90mA[39m::[0mCubicSpline[90m{Vector{Float64}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64, (1,)}[39m, [90mt[39m::[0mFloat64, [90miguess[39m::[0mFindFirstFunctions.Guesser[90m{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}[39m; [90mlb[39m::[0mInt64, [90mub_shift[39m::[0mInt64, [90midx_shift[39m::[0mInt64, [90mside[39m::[0mSymbol[0m[1m)[22m
[90m    @[39m [33mDataInterpolations[39m [90m~/.julia/packages/DataInterpolations/VgL0v/src/[39m[90m[4minterpolation_utils.jl:153[24m[39m
  [9] [0m[1mget_idx[22m
[90m    @[39m [90m~/.julia/packages/DataInterpolations/VgL0v/src/[39m[90m[4minterpolation_utils.jl:148[24m[39m[90m [inlined][39m
 [10] [0m[1m_interpolate[22m[0m[1m([22m[90mA[39m::[0mCubicSpline[90m{Vector{Float64}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64, (1,)}[39m, [90mt[39m::[0mFloat64, [90miguess[39m::[0mFindFirstFunctions.Guesser[90m{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}[39m[0m[1m)[22m
[90m    @[39m [33mDataInterpolations[39m [90m~/.julia/packages/DataInterpolations/VgL0v/src/[39m[90m[4minterpolation_methods.jl:159[24m[39m
 [11] [0m[1m_interpolate[22m[0m[1m([22m[90mA[39m::[0mCubicSpline[90m{Vector{Float64}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64, (1,)}[39m, [90mt[39m::[0mFloat64[0m[1m)[22m
[90m    @[39m [33mDataInterpolations[39m [90m~/.julia/packages/DataInterpolations/VgL0v/src/[39m[90m[4minterpolation_methods.jl:4[24m[39m
 [12] [0m[1mAbstractInterpolation[22m
[90m    @[39m [90m~/.julia/packages/DataInterpolations/VgL0v/src/[39m[90m[4mDataInterpolations.jl:24[24m[39m[90m [inlined][39m
 [13] [0m[1m(::var"#29#34"{CubicSpline{Vector{Float64}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Vector{Float64}, Float64, (1,)}})[22m[0m[1m([22m[90my[39m::[0mFloat64[0m[1m)[22m
[90m    @[39m [36mMain[39m [90m./[39m[90m[4mIn[3]:136[24m[39m
 [14] [0m[1m(::var"#objf#44"{Int64, Vector{Function}, var"#U#48"{Float64, Float64}, Vector{Float64}, Vector{Float64}, Float64})[22m[0m[1m([22m[90mz[39m::[0mVector[90m{Float64}[39m, [90mgrad[39m::[0mVector[90m{Float64}[39m[0m[1m)[22m
[90m    @[39m [36mMain[39m [90m./[39m[90m[4mIn[3]:355[24m[39m
 [15] [0m[1mnlopt_callback_wrapper[22m[0m[1m([22m[90mn[39m::[0mUInt32, [90mp_x[39m::[0mPtr[90m{Float64}[39m, [90mp_grad[39m::[0mPtr[90m{Float64}[39m, [90md_[39m::[0mPtr[90m{Nothing}[39m[0m[1m)[22m
[90m    @[39m [35mNLopt[39m [90m~/.julia/packages/NLopt/XaDCU/src/[39m[90m[4mNLopt.jl:415[24m[39m
 [16] [0m[1mnlopt_optimize[22m
[90m    @[39m [90m~/.julia/packages/NLopt/XaDCU/src/[39m[90m[4mlibnlopt.jl:132[24m[39m[90m [inlined][39m
 [17] [0m[1moptimize![22m[0m[1m([22m[90mo[39m::[0mOpt, [90mx[39m::[0mVector[90m{Float64}[39m[0m[1m)[22m
[90m    @[39m [35mNLopt[39m [90m~/.julia/packages/NLopt/XaDCU/src/[39m[90m[4mNLopt.jl:739[24m[39m
 [18] [0m[1moptimize[22m
[90m    @[39m [90m~/.julia/packages/NLopt/XaDCU/src/[39m[90m[4mNLopt.jl:753[24m[39m[90m [inlined][39m
 [19] [0m[1mget_policies_time0[22m[0m[1m([22m[90mT[39m::[0mBellmanEquation_Recursive[90m{Model{Float64, Matrix{Float64}, Vector{Float64}}, Int64, Float64}[39m, [90mB_[39m::[0mFloat64, [90ms0[39m::[0mInt64, [90mVf[39m::[0mVector[90m{Function}[39m, [90mxbar[39m::[0mVector[90m{Float64}[39m[0m[1m)[22m
[90m    @[39m [36mMain[39m [90m./[39m[90m[4mIn[3]:397[24m[39m
 [20] [0m[1mtime0_allocation[22m[0m[1m([22m[90mpab[39m::[0mRecursiveAllocation[90m{Model{Float64, Matrix{Float64}, Vector{Float64}}, Int64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, NTuple{4, Matrix{Function}}}[39m, [90mB_[39m::[0mFloat64, [90ms0[39m::[0mInt64[0m[1m)[22m
[90m    @[39m [36mMain[39m [90m./[39m[90m[4mIn[3]:165[24m[39m
 [21] [0m[1msimulate[22m[0m[1m([22m[90mpab[39m::[0mRecursiveAllocation[90m{Model{Float64, Matrix{Float64}, Vector{Float64}}, Int64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, NTuple{4, Matrix{Function}}}[39m, [90mB_[39m::[0mFloat64, [90ms_0[39m::[0mInt64, [90mT[39m::[0mInt64, [90msHist[39m::[0mVector[90m{Int64}[39m[0m[1m)[22m
[90m    @[39m [36mMain[39m [90m./[39m[90m[4mIn[3]:190[24m[39m
 [22] top-level scope
[90m    @[39m [90m[4mIn[5]:23[24m[39m
 [23] [0m[1meval[22m
[90m    @[39m [90m./[39m[90m[4mboot.jl:430[24m[39m[90m [inlined][39m
 [24] [0m[1minclude_string[22m[0m[1m([22m[90mmapexpr[39m::[0mtypeof(REPL.softscope), [90mmod[39m::[0mModule, [90mcode[39m::[0mString, [90mfilename[39m::[0mString[0m[1m)[22m
[90m    @[39m [90mBase[39m [90m./[39m[90m[4mloading.jl:2643[24m[39m
 [25] [0m[1msoftscope_include_string[22m[0m[1m([22m[90mm[39m::[0mModule, [90mcode[39m::[0mString, [90mfilename[39m::[0mString[0m[1m)[22m
[90m    @[39m [35mSoftGlobalScope[39m [90m~/.julia/packages/SoftGlobalScope/u4UzH/src/[39m[90m[4mSoftGlobalScope.jl:65[24m[39m
 [26] [0m[1mexecute_request[22m[0m[1m([22m[90msocket[39m::[0mZMQ.Socket, [90mmsg[39m::[0mIJulia.Msg[0m[1m)[22m
[90m    @[39m [36mIJulia[39m [90m~/.julia/packages/IJulia/bHdNn/src/[39m[90m[4mexecute_request.jl:67[24m[39m
 [27] [0m[1m#invokelatest#2[22m
[90m    @[39m [90m./[39m[90m[4messentials.jl:1055[24m[39m[90m [inlined][39m
 [28] [0m[1minvokelatest[22m
[90m    @[39m [90m./[39m[90m[4messentials.jl:1052[24m[39m[90m [inlined][39m
 [29] [0m[1meventloop[22m[0m[1m([22m[90msocket[39m::[0mZMQ.Socket[0m[1m)[22m
[90m    @[39m [36mIJulia[39m [90m~/.julia/packages/IJulia/bHdNn/src/[39m[90m[4meventloop.jl:8[24m[39m
 [30] [0m[1m(::IJulia.var"#15#18")[22m[0m[1m([22m[0m[1m)[22m
[90m    @[39m [36mIJulia[39m [90m~/.julia/packages/IJulia/bHdNn/src/[39m[90m[4meventloop.jl:38[24m[39m

Stacktrace:
 [1] optimize!(o::Opt, x::Vector{Float64})
   @ NLopt ~/.julia/packages/NLopt/XaDCU/src/NLopt.jl:746
 [2] optimize
   @ ~/.julia/packages/NLopt/XaDCU/src/NLopt.jl:753 [inlined]
 [3] get_policies_time0(T::BellmanEquation_Recursive{Model{Float64, Matrix{Float64}, Vector{Float64}}, Int64, Float64}, B_::Float64, s0::Int64, Vf::Vector{Function}, xbar::Vector{Float64})
   @ Main ./In[3]:397
 [4] time0_allocation(pab::RecursiveAllocation{Model{Float64, Matrix{Float64}, Vector{Float64}}, Int64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, NTuple{4, Matrix{Function}}}, B_::Float64, s0::Int64)
   @ Main ./In[3]:165
 [5] simulate(pab::RecursiveAllocation{Model{Float64, Matrix{Float64}, Vector{Float64}}, Int64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, NTuple{4, Matrix{Function}}}, B_::Float64, s_0::Int64, T::Int64, sHist::Vector{Int64})
   @ Main ./In[3]:190
 [6] top-level scope
   @ In[5]:23
```

**Comment by jlperla** [comment]
Fixed
