### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by Alim-faraji** [QuantEcon/lecture-julia.myst#7]
This is my stack trace when I turn the execution on:

←[91mException occurred:←[39;49;00m
  File "c:\users\user\anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 230, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named julia
←[91mThe full traceback has been saved in C:\Users\User\AppData\Local\Temp\sphinx-err-3fuvrsn5.log, if you want to report the issue to the developers.←[39;49;00m
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Traceback (most recent call last):
  File "c:\users\user\anaconda3\lib\site-packages\jupyter_book\sphinx.py", line 150, in build_sphinx
    app.build(force_all, filenames)
  File "c:\users\user\anaconda3\lib\site-packages\sphinx\application.py", line 348, in build
    self.builder.build_update()
  File "c:\users\user\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 297, in build_update
    self.build(to_build,
  File "c:\users\user\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "c:\users\user\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 418, in read
    self._read_serial(docnames)
  File "c:\users\user\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "c:\users\user\anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "c:\users\user\anaconda3\lib\site-packages\sphinx\io.py", line 221, in read_doc
    pub.publish()
  File "c:\users\user\anaconda3\lib\site-packages\docutils\core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "c:\users\user\anaconda3\lib\site-packages\sphinx\io.py", line 126, in read
    self.parse()
  File "c:\users\user\anaconda3\lib\site-packages\docutils\readers\__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "c:\users\user\anaconda3\lib\site-packages\myst_nb\parser.py", line 65, in parse
    ntbk = generate_notebook_outputs(
  File "c:\users\user\anaconda3\lib\site-packages\myst_nb\execution.py", line 136, in generate_notebook_outputs
    result = single_nb_execution(
  File "c:\users\user\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\user\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\client.py", line 537, in async_execute
    async with self.async_setup_kernel(**kwargs):
  File "c:\users\user\anaconda3\lib\site-packages\async_generator\_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\client.py", line 495, in async_setup_kernel
    await self.async_start_new_kernel(**kwargs)
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\client.py", line 407, in async_start_new_kernel
    await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\util.py", line 85, in ensure_async
    result = await obj
  File "c:\users\user\anaconda3\lib\site-packages\jupyter_client\manager.py", line 657, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "c:\users\user\anaconda3\lib\site-packages\jupyter_client\manager.py", line 292, in pre_start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "c:\users\user\anaconda3\lib\site-packages\jupyter_client\manager.py", line 210, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "c:\users\user\anaconda3\lib\site-packages\jupyter_client\manager.py", line 114, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "c:\users\user\anaconda3\lib\site-packages\jupyter_client\kernelspec.py", line 230, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named julia'

I'm not sure exactly what's happening. I should look into this.

**Comment by AakashGfude** [comment]
@Alim-faraji It seems like you dont have a `julia` kernel installed in your system for executing julia code in jupyterbook. Hence, the error. 
Try this https://github.com/JuliaLang/IJulia.jl

**Comment by Alim-faraji** [comment]
I think the issue was the name of julia. My system doesn't know the kernel named 'julia', it's named "julia-1.5".
