### ISSUE TITLE
Current Execution Failure [cache]

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-julia.myst#70]
The clean `cache` run is showing the following failures for:

1. `optgrowth`
2. `amss`

can anyone confirm if these are working for them locally?

```
WARNING: Execution Failed: /home/runner/work/lecture-julia.myst/lecture-julia.myst/lectures/dynamic_programming/optgrowth.md
321
WARNING: Execution Failed: /home/runner/work/lecture-julia.myst/lecture-julia.myst/lectures/dynamic_programming_squared/amss.md
322
```

**Comment by mmcky** [comment]
the `build logs` are showing

`amss`

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
@testset begin
  @test sim_seq_long_plot[50, 3] ≈ 0.3951985593686047
  @test sim_bel_long_plot[50, 3] ≈ 0.05684753244006188 atol = 1e-2
  @test sim_seq_long_plot[100, 4] ≈ 0.340233842670859
  @test sim_bel_long_plot[100, 4] ≈ 0.2093423366870517 atol = 1e-3
  @test sim_seq_long_plot[200, 2] ≈ 0.5839693539786998
  @test sim_bel_long_plot[200, 2] ≈ 0.6324036099550768 atol = 1e-3
end
------------------

[91mSome tests did not pass: 3 passed, 3 failed, 0 errored, 0 broken.[39m

Stacktrace:
 [1] finish(ts::Test.DefaultTestSet)
   @ Test /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:913
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1161 [inlined]
 [3] top-level scope
   @ In[11]:2
 [4] eval
   @ ./boot.jl:360 [inlined]
 [5] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094
LoadError: [91mSome tests did not pass: 3 passed, 3 failed, 0 errored, 0 broken.[39m
```

and `optgrowth` is showing:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
using Random
Random.seed!(42)
β = 0.94

Tw = similar(grid_y)
initial_w = 5 * log.(grid_y)
v_star_approx = fixedpoint(w -> T(w, grid_y, β, u, f, shocks),
                           initial_w).zero
Tw, σ = T(v_star_approx, grid_y, β, log, k -> k^α, shocks,
                         compute_policy = true)
σ_func = LinearInterpolation(grid_y, σ)
y = simulate_og(σ_func);

@testset begin
    @test y[5] ≈ 0.4896390574930345
    @test σ[3] ≈ 0.025084788719798193 atol = 1e-6
    @test Tw[4] ≈ -22.24681487036426
    @test v_star_approx[50] ≈ -17.76952387641302
end
------------------

[91mSome tests did not pass: 3 passed, 1 failed, 0 errored, 0 broken.[39m

Stacktrace:
 [1] finish(ts::Test.DefaultTestSet)
   @ Test /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:913
 [2] macro expansion
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1161 [inlined]
 [3] top-level scope
   @ In[20]:15
 [4] eval
   @ ./boot.jl:360 [inlined]
 [5] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094
LoadError: [91mSome tests did not pass: 3 passed, 1 failed, 0 errored, 0 broken.[39m
```

**Comment by mmcky** [comment]
@Alim-faraji @jlperla @jbrightuniverse 

For some reason my `local` clean build has `wald_friedman` failing while the cloud `cache` workflow has the above failing due to tests. 

```bash
Traceback (most recent call last):
  File "/Users/matthewmckay/anaconda3/envs/lecture-julia.myst/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/matthewmckay/anaconda3/envs/lecture-julia.myst/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/matthewmckay/anaconda3/envs/lecture-julia.myst/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/matthewmckay/anaconda3/envs/lecture-julia.myst/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/matthewmckay/anaconda3/envs/lecture-julia.myst/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/matthewmckay/anaconda3/envs/lecture-julia.myst/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/matthewmckay/anaconda3/envs/lecture-julia.myst/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/matthewmckay/anaconda3/envs/lecture-julia.myst/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
@testset "Comparative Statics" begin
    Random.seed!(0)
    @unpack d0, d1, L0, L1, c = Problem()
    α, β, outcomes, costs, trials = simulation(Problem(c = 2c, return_output = true))
    @test α ≈ 0.53551172 atol = 1e-3
    @test β ≈ 0.41244737 atol = 1e-3
    @test mean(outcomes) ≈ 0.39 atol = 1e-2
    @test mean(costs) ≈ 1.696 atol = 1e-3
    @test mean(trials) ≈ 1.19 atol = 1e-3
    choices = first.(choice.((clamp(β - eps(), 0, 1),
                              clamp(β + eps(), 0, 1),
                              clamp(α - eps(), 0, 1),
                              clamp(α + eps(), 0, 1)),
                              d0, d1, L0, L1, 2c))
    @test choices[1] == 2 
    @test choices[2] ≠ 2 
    @test choices[3] ≠ 1
    @test choices[4] == 1
end
------------------

[91mSome tests did not pass: 6 passed, 3 failed, 0 errored, 0 broken.[39m

Stacktrace:
 [1] finish(ts::Test.DefaultTestSet)
   @ Test /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:913
 [2] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1161 [inlined]
 [3] top-level scope
   @ In[9]:2
 [4] eval
   @ ./boot.jl:360 [inlined]
 [5] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1116
LoadError: [91mSome tests did not pass: 6 passed, 3 failed, 0 errored, 0 broken.[39m

```

**Comment by mmcky** [comment]
Could this be just small changes in the tolerances in floating point values between platforms?

**Comment by jlperla** [comment]
@mmcky  We will adjust these in #72 so that these are hopefully no longer an issue.  Those unit tests have already serverd their purpose.  Remaining ones should be detemrinistic.
