### ISSUE TITLE
Warnings after execution

### ISSUE THREAD

**Issue by Alim-faraji** [QuantEcon/lecture-julia.myst#9]
I build the notebooks with execution option turned on. These are the warning I got:
````bash
Running Jupyter-Book v0.10.2
Source Folder: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures
Config Path: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_config.yml
Output Path: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html
Running Sphinx v3.1.2
WARNING: favicon file '_static/lectures-favicon.ico' does not exist
checking for C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_static\quant-econ.bib in bibtex cache... not found
parsing bibtex file C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_static\quant-econ.bib... parsed 153 entries
myst v0.13.7: MdParserConfig(renderer='sphinx', commonmark_only=False, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, update_mathjax=True, enable_extensions=['colon_fence', 'dollarmath', 'linkify', 'substitution'], disable_syntax=[], url_schemes=['mailto', 'http', 'https'], heading_anchors=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'])
sphinx-multitoc-numbering v0.1.3: Loaded
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 68 source files that are out of date
updating environment: [new config] 68 added, 0 changed, 0 removed
Executing: about_lectures in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures
Starting kernel event loops.
Executing: continuous_time/covid_sde in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\continuous_time
Starting kernel event loops.
Executing: continuous_time/seir_model in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\continuous_time
Starting kernel event loops.
Executing: dynamic_programming/career in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/coleman_policy_iter in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/discrete_dp in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/egm_policy_iter in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/ifp in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/jv in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/lqcontrol in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/mccall_model in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/mccall_model_with_separation in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/odu in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/optgrowth in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/perm_income in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/perm_income_cons in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/robustness in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/short_path in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/smoothing in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming/wald_friedman in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming
Starting kernel event loops.
Executing: dynamic_programming_squared/amss in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming_squared
Starting kernel event loops.
Executing: dynamic_programming_squared/dyn_stack in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming_squared
Starting kernel event loops.
Executing: dynamic_programming_squared/lqramsey in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming_squared
Starting kernel event loops.
Executing: dynamic_programming_squared/opt_tax_recur in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming_squared
Starting kernel event loops.
Executing: getting_started_julia/fundamental_types in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia
Starting kernel event loops.
Executing: getting_started_julia/getting_started in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia
Starting kernel event loops.
Executing: getting_started_julia/introduction_to_types in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia
Starting kernel event loops.
Executing: getting_started_julia/julia_by_example in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia
Starting kernel event loops.
Executing: getting_started_julia/julia_environment in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia
Starting kernel event loops.
Executing: getting_started_julia/julia_essentials in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia
Starting kernel event loops.
Executing: intro in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures
Executing: more_julia/data_statistical_packages in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\more_julia
Starting kernel event loops.
Executing: more_julia/general_packages in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\more_julia
Starting kernel event loops.
Executing: more_julia/generic_programming in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\more_julia
Starting kernel event loops.
Executing: more_julia/need_for_speed in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\more_julia
Starting kernel event loops.
Executing: more_julia/optimization_solver_packages in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\more_julia
Starting kernel event loops.
Executing: more_julia/testing in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\more_julia
Starting kernel event loops.
Executing: more_julia/tools_editors in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\more_julia
Starting kernel event loops.
Executing: more_julia/version_control in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\more_julia
Starting kernel event loops.
Executing: multi_agent_models/aiyagari in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\multi_agent_models
Starting kernel event loops.
Executing: multi_agent_models/arellano in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\multi_agent_models
Starting kernel event loops.
Executing: multi_agent_models/harrison_kreps in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\multi_agent_models
Starting kernel event loops.
Executing: multi_agent_models/lake_model in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\multi_agent_models
Starting kernel event loops.
Executing: multi_agent_models/lucas_model in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\multi_agent_models
Starting kernel event loops.
Executing: multi_agent_models/markov_asset in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\multi_agent_models
Starting kernel event loops.
Executing: multi_agent_models/markov_perf in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\multi_agent_models
Starting kernel event loops.
Executing: multi_agent_models/matsuyama in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\multi_agent_models
Starting kernel event loops.
Executing: multi_agent_models/rational_expectations in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\multi_agent_models
Starting kernel event loops.
Executing: multi_agent_models/schelling in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\multi_agent_models
Starting kernel event loops.
Executing: multi_agent_models/uncertainty_traps in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\multi_agent_models
Starting kernel event loops.
Executing: status in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures
Starting kernel event loops.
Executing: time_series_models/additive_functionals in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\time_series_models
Starting kernel event loops.
Executing: time_series_models/arma in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\time_series_models
Starting kernel event loops.
Executing: time_series_models/classical_filtering in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\time_series_models
Starting kernel event loops.
Executing: time_series_models/estspec in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\time_series_models
Starting kernel event loops.
Executing: time_series_models/lu_tricks in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\time_series_models
Starting kernel event loops.
Executing: time_series_models/multiplicative_functionals in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\time_series_models
Starting kernel event loops.
Executing: tools_and_techniques/finite_markov in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques
Starting kernel event loops.
Executing: tools_and_techniques/iterative_methods_sparsity in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques
Starting kernel event loops.
Executing: tools_and_techniques/kalman in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques
Starting kernel event loops.
Executing: tools_and_techniques/linear_algebra in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques
Starting kernel event loops.
Executing: tools_and_techniques/linear_models in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques
Starting kernel event loops.
Executing: tools_and_techniques/lln_clt in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques
Starting kernel event loops.
Executing: tools_and_techniques/numerical_linear_algebra in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques
Starting kernel event loops.
Executing: tools_and_techniques/orth_proj in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques
Starting kernel event loops.
Executing: tools_and_techniques/stationary_densities in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques
Starting kernel event loops.
Executing: troubleshooting in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures
Starting kernel event loops.
Executing: zreferences in: C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures
Starting kernel event loops.

WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\ifp.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\lqcontrol.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\mccall_model_with_separation.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\optgrowth.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\perm_income.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\wald_friedman.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\lqramsey.log
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia\introduction_to_types.md:532: WARNING: Found an unexpected `code-cell` directive. Either this file was not converted to a notebook, because Jupytext header content was missing, or the `code-cell` was not converted, because it is nested. See https://myst-nb.readthedocs.io/en/latest/use/markdown.html for more information.
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia\introduction_to_types.md:560: WARNING: Found an unexpected `code-cell` directive. Either this file was not converted to a notebook, because Jupytext header content was missing, or the `code-cell` was not converted, because it is nested. See https://myst-nb.readthedocs.io/en/latest/use/markdown.html for more information.
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia\introduction_to_types.md:574: WARNING: Found an unexpected `code-cell` directive. Either this file was not converted to a notebook, because Jupytext header content was missing, or the `code-cell` was not converted, because it is nested. See https://myst-nb.readthedocs.io/en/latest/use/markdown.html for more information.
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia\introduction_to_types.md:581: WARNING: Found an unexpected `code-cell` directive. Either this file was not converted to a notebook, because Jupytext header content was missing, or the `code-cell` was not converted, because it is nested. See https://myst-nb.readthedocs.io/en/latest/use/markdown.html for more information.
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia\introduction_to_types.md:590: WARNING: Found an unexpected `code-cell` directive. Either this file was not converted to a notebook, because Jupytext header content was missing, or the `code-cell` was not converted, because it is nested. See https://myst-nb.readthedocs.io/en/latest/use/markdown.html for more information.
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia\introduction_to_types.md:608: WARNING: Found an unexpected `code-cell` directive. Either this file was not converted to a notebook, because Jupytext header content was missing, or the `code-cell` was not converted, because it is nested. See https://myst-nb.readthedocs.io/en/latest/use/markdown.html for more information.
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia\introduction_to_types.md:620: WARNING: Found an unexpected `code-cell` directive. Either this file was not converted to a notebook, because Jupytext header content was missing, or the `code-cell` was not converted, because it is nested. See https://myst-nb.readthedocs.io/en/latest/use/markdown.html for more information.
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\tools_editors.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\lake_model.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\uncertainty_traps.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\additive_functionals.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\arma.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\estspec.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\multiplicative_functionals.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\finite_markov.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\linear_models.log
WARNING: Execution Failed with traceback saved in C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\reports\stationary_densities.log
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques\stationary_densities.md:837: WARNING: Non-consecutive header level increase; 1 to 3 [myst.header]
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] zreferences
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming\smoothing.md:65: WARNING: unknown document: dynamic_programming/perm_income_cons
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming\smoothing.md:80: WARNING: unknown document: dynamic_programming/perm_income_cons
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming_squared\dyn_stack.md:838: WARNING: Could not lex literal_block as "julia". Highlighting skipped.
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia\getting_started.md:107: WARNING: 'myst' reference target not found: x-github-client://openRepo/https://github.com/QuantEcon/quantecon-notebooks-julia
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia\julia_essentials.md:23: WARNING: Could not lex literal_block as "julia". Highlighting skipped.
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\more_julia\testing.md:538: WARNING: Could not lex literal_block as "julia". Highlighting skipped.
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\time_series_models\classical_filtering.md:392: WARNING: unknown document: time_series_models/lu_tricks
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\time_series_models\classical_filtering.md:578: WARNING: unknown document: time_series_models/lu_tricks
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques\kalman.md:464: WARNING: 'myst' reference target not found: 
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques\numerical_linear_algebra.md:43: WARNING: unknown document: ../getting_starting_julia/introduction_to_types
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques\numerical_linear_algebra.md:458: WARNING: undefined label: qr_decomposition (if the link has no caption the label must precede a section header)     
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques\numerical_linear_algebra.md:471: WARNING: undefined label: qr_decomposition (if the link has no caption the label must precede a section header)     
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\tools_and_techniques\numerical_linear_algebra.md:570: WARNING: unknown document: mc
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [100%] C:/Users/User/Documents/GitHub/lecture-julia-myst/lecture-julia.myst/lectures/_build/jupyter_execute/tools_and_techniques\stationary_densities_8_0.png0.pngpng
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 39 warnings.

The HTML pages are in lectures\_build\html.
Writing redirects...

===============================================================================

Finished generating HTML for book.
Your book's HTML pages are here:
    lectures\_build\html\
You can look at your book by opening this file in a browser:
    lectures\_build\html\index.html
Or paste this line directly into your browser bar:
    file://C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\_build\html\index.html

===============================================================================
````

**Comment by AakashGfude** [comment]
@Alim-faraji can you have a look at the log files mentioned in these warnings. And paste it here if it's anything apart from missing packages.

**Comment by Alim-faraji** [comment]
I'm not sure exactly why some tests are failing. This is a sample log:
````bash
Traceback (most recent call last):
  File "c:\users\user\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\user\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\user\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
@testset begin
  @test path.p[3] ≈ 1.5395294981420302 # randomness check.
  @test path.g[31] ≈ 0.31995784745763833 # stuff we plot
  @test path.c[36] ≈ 0.6387556584133354
  @test path.B[9] ≈ 0.07442403655989423
  @test path.rvn[27] ≈ 0.35087848425010165
  @test path.π[31] ≈ 0.002863930880184773
  @test path.R[43] ≈ 1.055269758955539
  @test path.ξ[43] ≈ 0.9867651305840917
  @test path.Π[43] ≈ -0.18634133373855144 # plot tests
end
------------------

[91mSome tests did not pass: 2 passed, 7 failed, 0 errored, 0 broken.[39m

Stacktrace:
 [1] finish(::Test.DefaultTestSet) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Test\src\Test.jl:879
 [2] top-level scope at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Test\src\Test.jl:1125
 [3] top-level scope at In[5]:2
 [4] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091
LoadError: [91mSome tests did not pass: 2 passed, 7 failed, 0 errored, 0 broken.[39m

````

**Comment by Alim-faraji** [comment]
````bash
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia\introduction_to_types.md:532: WARNING: Found an unexpected `code-cell` directive. Either this file was not converted to a notebook, because Jupytext header content was missing, or the `code-cell` was not converted, because it is nested. See https://myst-nb.readthedocs.io/en/latest/use/markdown.html for more information.
````
These come from spaces before `{code-cell}`s. The builds recognizes it as a nested code.

**Comment by Alim-faraji** [comment]
````bash
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\dynamic_programming_squared\dyn_stack.md:838: WARNING: Could not lex literal_block as "julia". Highlighting skipped.
````
What is this warning?

**Comment by Alim-faraji** [comment]
````bash
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\getting_started_julia\getting_started.md:107: WARNING: 'myst' reference target not found: x-github-client://openRepo/https://github.com/QuantEcon/quantecon-notebooks-julia
````
The link doesn't work.

**Comment by Alim-faraji** [comment]
These links to other docs need to be changed. 
````bash
C:\Users\User\Documents\GitHub\lecture-julia-myst\lecture-julia.myst\lectures\time_series_models\classical_filtering.md:392: WARNING: unknown document: time_series_models/lu_tricks
````
