### ISSUE TITLE
Fix data and statistics packages

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#95]
With the testing branch in #63  which includes a package bump, the output says
```
Traceback (most recent call last):
  File "c:\users\jesse\anaconda3\envs\lecture-julia.myst\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\jesse\anaconda3\envs\lecture-julia.myst\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\jesse\anaconda3\envs\lecture-julia.myst\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\jesse\anaconda3\envs\lecture-julia.myst\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\jesse\anaconda3\envs\lecture-julia.myst\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\jesse\anaconda3\envs\lecture-julia.myst\lib\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "c:\users\jesse\anaconda3\envs\lecture-julia.myst\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\jesse\anaconda3\envs\lecture-julia.myst\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
using DataFrames, RDatasets  # RDatasets provides good standard data examples from R

# note use of missing
commodities = ["crude", "gas", "gold", "silver"]
last_price = [4.2, 11.3, 12.1, missing]
df = DataFrame(commod = commodities, price = last_price)
------------------

importing DataFrames into Main conflicts with an existing identifier

Stacktrace:
 [1] eval
   @ .\boot.jl:360 [inlined]
 [2] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1094
LoadError: importing DataFrames into Main conflicts with an existing identifier

```

**Comment by jlperla** [comment]
@jbrightuniverse  Sorry about that.  I think I will close in so we can do #97 instead, which is part of a more general topic.
